# This is a basic workflow to help you get started with Actions

name: Build-adservice

on:
  push:
    branches: [ master ]
    paths:
      - "eshopping/src/adservice/**"
  pull_request:
     branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ACR build
        id: acr
        uses: ams0/acr-task-github-action@v2
        with:
          service_principal: ${{ secrets.service_principal }}
          service_principal_password: ${{ secrets.service_principal_password }}
          tenant: ${{ secrets.tenant }}
          registry: ${{ secrets.registry }}
          repository: adservice
          # image: adservice
          tag: ${{github.run_number}}
          # git_access_token: ${{ secrets.git_access_token }}
          folder: eshopping/src/adservice
          dockerfile: dockerfiles
