name: Build-adservice
on:
  push:
    branches: [ master ]
    paths:
      - "eshopping/src/adservice/**"
  pull_request:
     branches: [ master ]

env:
  RESOURCEGROUPNAME: "secret-store-csi-aks-akv-rg"
  IMAGENAME: "adservice"
  REGISTRYNAME: "prod03acreg"
  APPATH: "eshopping/src/adservice"
  CLUSTERNAME: "secret-store-csi-aks-akv"


jobs:
  build:
    name: Build and push image to container registry
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
        # login to azure
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRYNAME }}.azurecr.io
        username: ${{ secrets.acr_prod03acreg_username }}
        password: ${{ secrets.acr_prod03acreg_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build $GITHUB_WORKSPACE/${{ env.APPATH }} -f  ${{ env.APPATH }}/Dockerfile -t ${{ env.REGISTRYNAME }}.azurecr.io/${{ env.IMAGENAME }}:${{ github.sha }}
        docker push ${{ env.REGISTRYNAME }}.azurecr.io/${{ env.IMAGENAME }}:${{ github.sha }}   